[credential:__REST_CREDENTIAL__#JAMF-Pro-addon-for-splunk#configs/conf-jamf_pro_addon_for_splunk_settings:proxy``splunk_cred_sep``1:]
password = $7$TIF8GdSAITD/WeZVrp7vzaBDzfRzdf44sXVpBBOfz0r/qngfI2PQhv93wF0btH8IrzjmTTSUBrg+2/0=

[credential:__REST_CREDENTIAL__#JAMF-Pro-addon-for-splunk#configs/conf-jamf_pro_addon_for_splunk_settings:proxy``splunk_cred_sep``2:]
password = $7$Lnq42XfagHmOs6fISYsduzjTqjivSUdB3+hi+Kh3n64535dw4HiD8AG+awSglY9RSDJk/uceTTLv/0vvkudNj+cKIyj1k/kfCudKyYs6oepP25qegjW7pmkkLdhC+gnjonYwnkM010uN5/84PoBEw75TmwMiprGLnOWlz7YnkM3+PSNcPjR0pYuhhh4mqYf0BGEzimUCFuTZOf+mA4pOcCwhTzccbR2L0PBV

[credential:__REST_CREDENTIAL__#JAMF-Pro-addon-for-splunk#data/inputs/jamf:test1``splunk_cred_sep``1:]
password = $7$CdXtYJmRZCRCu6i1+dRdmHeQyo9hadNfE5ie1TSl82EB9SShkN3CiYQQgsvdQ+LEX84/oQ==

[credential:__REST_CREDENTIAL__#JAMF-Pro-addon-for-splunk#data/inputs/jamf:test1``splunk_cred_sep``2:]
password = $7$ewBlr6U4RguP7Wdh+8ef2O9KdsCJgg3qFOTBJdCF+1qYyc2QoIul2d3uUmKfuaR8mqUadon5yjosiiHv0Ec9e1ACoqtpmKKRnq3gKcweTiGzsWvO3tTpaQ5M2G3mH6xNAGhG7H3AJJ+q4Nje04BN/Sx0EPRVTWbn0BZBXNppmmCP3bge4J+nDXHRRYpUAUuAD+vYhUFYSHK5qL3wWGw/w0BQZn/0+AL2LDFL
