##
## SPDX-FileCopyrightText: 2021 Splunk LLC <sales@splunk.com>
## SPDX-License-Identifier: LicenseRef-Splunk-8-2021
##
##
[awssnsalert]
filename = command_sns_search_alert.py
chunked = true
python.version = python3.9
python.required = 3.9, 3.13

[listawsaccounts]
passauth = true
enableheader = true
filename = command_list_accounts.py
python.version = python3.9
python.required = 3.9, 3.13

[listawsinputs]
passauth = true
enableheader = true
filename = command_list_inputs.py
python.version = python3.9
python.required = 3.9, 3.13
