[install]
is_configured = 1
state = enabled

[ui]
is_visible = 1
label = Unicode NFC Normalizer

[launcher]
author = Splunk Administrator
description = Automatically normalizes configured macOS NFD field values to NFC using an External Lookup.
version = 2.0.0
