[role_admin]
edit_log_alert_event = disabled
edit_messages = disabled
grantableRoles = admin
importRoles = can_delete;power;user
list_field_filter = disabled
search_process_config_refresh = disabled
srchMaxTime = 8640000
