[general]
serverName = jmoh141
pass4SymmKey = $7$qBRwgCwZ93mNPu6NSf/dRdy2+RzSOyXjFaDCdX85aKobGHIFNS+dQg==

[sslConfig]
sslPassword = $7$ZdqdpBelRUXPpD3ZBY1yYQ8+BAuK+tUeSWj3ObLpIAoDzVF8zqqi5Q==

[lmpool:auto_generated_pool_download-trial]
description = auto_generated_pool_download-trial
peers = *
quota = MAX
stack_id = download-trial

[lmpool:auto_generated_pool_forwarder]
description = auto_generated_pool_forwarder
peers = *
quota = MAX
stack_id = forwarder

[lmpool:auto_generated_pool_free]
description = auto_generated_pool_free
peers = *
quota = MAX
stack_id = free
