[test]
coldPath = $SPLUNK_DB/test/colddb
homePath = $SPLUNK_DB/test/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/test/thaweddb

[test1]
coldPath = $SPLUNK_DB/test1/colddb
homePath = $SPLUNK_DB/test1/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/test1/thaweddb
