[*]

[(?::){0}*]

[defualt]

[...]

[test10]
DATETIME_CONFIG = 
KV_MODE = auto
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = true
category = Custom
pulldown_type = true
AUTO_KV_JSON = false
REPORT-json-string-fields = json_string_fields
