[test]
action.email.useNSSubject = 1
action.rfes_ar_links.param.risk = 0
action.webhook.enable_allowlist = 0
alert.track = 0
cron_schedule = 28 12 * * *
enableSched = 1
search = index=_internal | head 1\
| stats count by sourcetype\
| collect index=test
